export const createProject = 'Projects';
export const viewProjects = 'Projects';
export const viewProject = (id) => `Projects/${id}`;
export const deleteProject = (id) => `Projects/${id}`;
export const editProject = (id) => `Projects/${id}`;
export const projectSummary = (id) => `Projects/${id}/summary`;
export const projectDetails = (id) => `Projects/${id}/details`;
export const updateProject = (id) => 'ProjectUpdates';
export const showProjectUpdate = (id) => `ProjectUpdates/${id}`;
export const editProjectUpdate = (id) => `ProjectUpdates/${id}`;
