const constants = {
  APPLY_PENDING: 'APPLY_PENDING',
  APPLY_SUCCESS: 'APPLY_SUCCESS',
  APPLY_FAILURE: 'APPLY_FAILURE',

  REGISTER_PENDING: 'REGISTER_PENDING',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  VERIFY_INDIVIDUAL_PENDING: 'VERIFY_INDIVIDUAL_PENDING',
  VERIFY_INDIVIDUAL_SUCCESS: 'VERIFY_INDIVIDUAL_SUCCESS',
  VERIFY_INDIVIDUAL_FAILURE: 'VERIFY_INDIVIDUAL_FAILURE',

  VERIFY_CORPORATE_PENDING: 'VERIFY_CORPORATE_PENDING',
  VERIFY_CORPORATE_SUCCESS: 'VERIFY_CORPORATE_SUCCESS',
  VERIFY_CORPORATE_FAILURE: 'VERIFY_CORPORATE_FAILURE',

  VERIFY_ACCOUNT_OTP_PENDING: 'VERIFY_ACCOUNT_OTP_PENDING',
  VERIFY_ACCOUNT_OTP_SUCCESS: 'VERIFY_ACCOUNT_OTP_SUCCESS',
  VERIFY_ACCOUNT_OTP_FAILURE: 'VERIFY_ACCOUNT_OTP_FAILURE',

  SEND_ACCOUNT_OTP_PENDING: 'SEND_ACCOUNT_OTP_PENDING',
  SEND_ACCOUNT_OTP_SUCCESS: 'SEND_ACCOUNT_OTP_SUCCESS',
  SEND_ACCOUNT_OTP_FAILURE: 'SEND_ACCOUNT_OTP_FAILURE',

  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  CHANGE_PASSWORD_PENDING: 'CHANGE_PASSWORD_PENDING',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  FORGOT_PASSWORD_PENDING: 'FORGOT_PASSWORD_PENDING',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  RESET_PASSWORD_PENDING: 'RESET_PASSWORD_PENDING',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  UPLOAD_LOGO_PENDING: 'UPLOAD_LOGO_PENDING',
  UPLOAD_LOGO_PROGRESS: 'UPLOAD_LOGO_PROGRESS',
  UPLOAD_LOGO_SUCCESS: 'UPLOAD_LOGO_SUCCESS',
  UPLOAD_LOGO_FAILURE: 'UPLOAD_LOGO_FAILURE',

  PROJECT_PENDING: 'PROJECT_PENDING',
  PROJECT_SUCCESS: 'PROJECT_SUCCESS',
  PROJECT_FAILURE: 'PROJECT_FAILURE',

  INCOMPLETE_PROJECTS_PENDING: 'INCOMPLETE_PROJECTS_PENDING',
  INCOMPLETE_PROJECTS_SUCCESS: 'INCOMPLETE_PROJECTS_SUCCESS',
  INCOMPLETE_PROJECTS_FAILURE: 'INCOMPLETE_PROJECTS_FAILURE',

  SUBMIT_PROJECT_PENDING: 'SUBMIT_PROJECT_PENDING',
  SUBMIT_PROJECT_SUCCESS: 'SUBMIT_PROJECT_SUCCESS',
  SUBMIT_PROJECT_FAILURE: 'SUBMIT_PROJECT_FAILURE',

  DELETE_PROJECT_PENDING: 'DELETE_PROJECT_PENDING',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_FAILURE: 'DELETE_PROJECT_FAILURE',

  EDIT_PROJECT_SUCCESS: 'EDIT_PROJECT_SUCCESS',
  EDIT_PROJECT_FAILURE: 'EDIT_PROJECT_FAILURE',
  EDIT_PROJECT_PENDING: 'EDIT_PROJECT_PENDING',

  PROJECT_DETAILS_PENDING: 'PROJECT_DETAILS_PENDING',
  PROJECT_DETAILS_SUCCESS: 'PROJECT_DETAILS_SUCCESS',
  PROJECT_DETAILS_FAILURE: 'PROJECT_DETAILS_FAILURE',

  PROJECT_SUMMARY_PENDING: 'PROJECT_SUMMARY_PENDING',
  PROJECT_SUMMARY_SUCCESS: 'PROJECT_SUMMARY_SUCCESS',
  PROJECT_SUMMARY_FAILURE: 'PROJECT_SUMMARY_FAILURE',

  UPDATE_PROJECT_PENDING: 'UPDATE_PROJECT_PENDING',
  UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',
  UPDATE_PROJECT_FAILURE: 'UPDATE_PROJECT_FAILURE',

  PROJECT_UPDATES_PENDING: 'PROJECT_UPDATES_PENDING',
  PROJECT_UPDATES_SUCCESS: 'PROJECT_UPDATES_SUCCESS',
  PROJECT_UPDATES_FAILURE: 'PROJECT_UPDATES_FAILURE',

  EDIT_PROJECT_UPDATES_PENDING: 'EDIT_PROJECT_UPDATES_PENDING',
  EDIT_PROJECT_UPDATES_SUCCESS: 'EDIT_PROJECT_UPDATES_SUCCESS',
  EDIT_PROJECT_UPDATES_FAILURE: 'EDIT_PROJECT_UPDATES_FAILURE'

};

export default constants;
