const constants = {
  APPLY_PENDING: 'APPLY_PENDING',
  APPLY_SUCCESS: 'APPLY_SUCCESS',
  APPLY_FAILURE: 'APPLY_FAILURE',

  PROCESS_BANK_STATEMENT_PENDING: 'PROCESS_BANK_STATEMENT_PENDING',
  PROCESS_BANK_STATEMENT_SUCCESS: 'PROCESS_BANK_STATEMENT_SUCCESS',
  PROCESS_BANK_STATEMENT_FAILURE: 'PROCESS_BANK_STATEMENT_FAILURE',

  PROCESS_UPLOADED_STATEMENT_PENDING: 'PROCESS_UPLOADED_STATEMENT_PENDING',
  PROCESS_UPLOADED_STATEMENT_SUCCESS: 'PROCESS_UPLOADED_STATEMENT_SUCCESS',
  PROCESS_UPLOADED_STATEMENT_FAILURE: 'PROCESS_UPLOADED_STATEMENT_FAILURE',

  UPDATE_LOAN_OFFER_PENDING: 'UPDATE_LOAN_OFFER_PENDING',
  UPDATE_LOAN_OFFER_SUCCESS: 'UPDATE_LOAN_OFFER_SUCCESS',
  UPDATE_LOAN_OFFER_FAILURE: 'UPDATE_LOAN_OFFER_FAILURE',

  LOAN_OFFER_DETAILS_PENDING: 'LOAN_OFFER_DETAILS_PENDING',
  LOAN_OFFER_DETAILS_SUCCESS: 'LOAN_OFFER_DETAILS_SUCCESS',
  LOAN_OFFER_DETAILS_FAILURE: 'LOAN_OFFER_DETAILS_FAILURE',

  LOAN_OFFER_ACCEPTANCE_PENDING: 'LOAN_OFFER_ACCEPTANCE_PENDING',
  LOAN_OFFER_ACCEPTANCE_SUCCESS: 'LOAN_OFFER_ACCEPTANCE_SUCCESS',
  LOAN_OFFER_ACCEPTANCE_FAILURE: 'LOAN_OFFER_ACCEPTANCE_FAILURE',

  LOAN_DISBURSED_PENDING: 'LOAN_DISBURSED_PENDING',
  LOAN_DISBURSED_SUCCESS: 'LOAN_DISBURSED_SUCCESS',
  LOAN_DISBURSED_FAILURE: 'LOAN_DISBURSED_FAILURE',

  GET_APPLICATIONS_DETAILS_PENDING: 'GET_APPLICATIONS_DETAILS_PENDING',
  GET_APPLICATIONS_DETAILS_SUCCESS: 'GET_APPLICATIONS_DETAILS_SUCCESS',
  GET_APPLICATIONS_DETAILS_FAILURE: 'GET_APPLICATIONS_DETAILS_FAILURE',

  GET_APPLICATION_DETAILS_PENDING: 'GET_APPLICATION_DETAILS_PENDING',
  GET_APPLICATION_DETAILS_SUCCESS: 'GET_APPLICATION_DETAILS_SUCCESS',
  GET_APPLICATION_DETAILS_FAILURE: 'GET_APPLICATION_DETAILS_FAILURE',

  GET_BANK_LIST_PENDING: 'GET_BANK_LIST_PENDING',
  GET_BANK_LIST_SUCCESS: 'GET_BANK_LIST_SUCCESS',
  GET_BANK_LIST_FAILURE: 'GET_BANK_LIST_FAILURE'
};

export default constants;
